-- General Settings
vim.opt.termbidi = true                                   -- Fix for BiDi text (Arabic/Hindi)
vim.g.javascript_indent_disable = 1
vim.opt.number = true                                     -- Enable absolute line numbers
vim.opt.relativenumber = false                            -- Enable relative line numbers
vim.opt.tabstop = 4                                       -- Set tab width to 4 spaces
vim.opt.shiftwidth = 4                                    -- Set indentation width to 4 spaces
vim.opt.expandtab = true                                  -- Use spaces instead of tabs
vim.opt.smartindent = true                                -- Enable smart indentation
vim.opt.autoindent = true                                 -- Enable automatic indentation for new lines
vim.opt.termguicolors = true                              -- Enable true color support
vim.opt.mouse = "a"                                       -- Enable mouse support
vim.opt.clipboard = "unnamedplus"                         -- Sync with system clipboard
vim.opt.fileencoding = "utf-8"                            -- Ensure files are written in UTF-8
vim.opt.encoding = "utf-8"                                -- Set internal encoding (redundant but explicit)
vim.opt.textwidth = 0
vim.opt.wrap = false                                      -- Disable wrapping completely
vim.opt.cursorline = false                                -- Highlight the current line
vim.opt.incsearch = true                                  -- Show search matches as you type
vim.opt.hlsearch = true                                   -- Highlight all search results
vim.opt.ignorecase = true                                 -- Ignore case during searches
vim.opt.smartcase = true                                  -- Override ignorecase if search contains uppercase
vim.opt.completeopt = { "menuone", "noselect" }           -- Customize completion behavior
vim.opt.wildmenu = true                                   -- Enable command-line completion menu
vim.opt.wildmode = "longest:full,full"                    -- Command-line completion mode: shell-like
vim.opt.undofile = true                                   -- Enable persistent undo across sessions
vim.opt.undodir = vim.fn.expand("~/.config/nvim/undodir") -- Specify undo directory
vim.opt.showmode = false                                  -- Hide mode indicator
vim.opt.laststatus = 2                                    -- Always show status line
vim.opt.scrolloff = 8                                     -- Keep 8 lines above/below cursor
vim.opt.autoread = true                                     -- Automatically reload files changed outside
vim.opt.updatetime = 250
